Repository IBM/mcp-context-forge, pull requests merged in 2025-08, with the labels that each got.

#686 feat: Add tool_pre_invoke and tool_post_invoke plugin hooks
  docs/docs/using/plugins/index.md
  mcpgateway/db.py
  mcpgateway/plugins/framework/base.py
  mcpgateway/plugins/framework/manager.py
  mcpgateway/plugins/framework/models.py
  mcpgateway/plugins/framework/plugin_types.py
  mcpgateway/plugins/framework/utils.py
  mcpgateway/services/tool_service.py
  plugins/config.yaml
  plugins/pii_filter/pii_filter.py
  plugins/pii_filter/plugin-manifest.yaml
  plugins/regex_filter/search_replace.py
  tests/unit/mcpgateway/plugins/fixtures/configs/valid_tool_hooks.yaml
  tests/unit/mcpgateway/plugins/framework/test_manager.py
Labels: enhancement

#767 fix: local network address translation in discovery module
  mcpgateway/federation/discovery.py
Labels: bug

#783 fix: plugins template
  .pre-commit-config.yaml
  docs/docs/using/plugins/lifecycle.md
  mcpgateway/plugins/tools/cli.py
  plugin_templates/external/Makefile.jinja
  plugin_templates/external/README.md.jinja
  plugin_templates/external/pyproject.toml.jinja
Labels: bug

#791 docs: update plugins dev workflow
  docs/docs/using/plugins/lifecycle.md
Labels: documentation

#800 Fix oauth tool write to db
  mcpgateway/services/gateway_service.py
  tests/unit/mcpgateway/test_main.py
Labels: bug
