Repository IBM/mcp-context-forge, pull requests merged in 2025-07, with the labels that each got.

#487 Update admin.js as per issue #352
  mcpgateway/static/admin.js
Labels: bug, frontend

#553 Input validation testing closes #552
  mcpgateway/config.py
  mcpgateway/schemas.py
  mcpgateway/validators.py
  tests/security/test_input_validation.py
Labels: testing, security

#632 425 SECURITYFEATURE Make JWT Token Expiration Mandatory when REQUIRE_TOKEN_EXPIRATION=true
  .env.example
  mcpgateway/config.py
  mcpgateway/utils/create_jwt_token.py
  mcpgateway/utils/verify_credentials.py
  tests/unit/mcpgateway/utils/test_verify_credentials.py
Labels: bug
